@extends('admin.layouts.app',['title'=>'Return Request #'.$returnRequest->id,'heading'=>'Return Request #'.$returnRequest->id])
@section('content')<div class="grid gap-6 lg:grid-cols-[1fr_360px]"><section class="space-y-6"><div class="rounded-2xl border border-black bg-white p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-widest text-emerald-600">{{ ucfirst($returnRequest->request_type) }}</p><h2 class="mt-1 text-2xl font-black">{{ ucwords(str_replace('_',' ',$returnRequest->reason)) }}</h2><p class="mt-2 text-sm text-black">Order {{ $returnRequest->order->order_number ?? '—' }} · {{ $returnRequest->user->name ?? '—' }}</p></div><span class="rounded-full bg-white px-3 py-1 text-xs font-bold">{{ ucwords(str_replace('_',' ',$returnRequest->status)) }}</span></div><div class="mt-6 border-t border-black pt-6"><p class="text-xs font-bold uppercase tracking-wider text-black">Customer notes</p><p class="mt-2 whitespace-pre-wrap text-sm leading-6 text-black">{{ $returnRequest->notes ?: 'No notes provided.' }}</p></div></div><div class="rounded-2xl border border-black bg-white p-6"><h3 class="font-bold">Requested items</h3><div class="mt-4 divide-y divide-black">@foreach($returnRequest->order->items->whereIn('id',$returnRequest->order_item_ids ?? []) as $item)<div class="flex justify-between py-3 text-sm"><span>{{ $item->product_name }} · {{ $item->size }} / {{ $item->color }}</span><span class="font-bold">×{{ $item->quantity }}</span></div>@endforeach</div></div></section><aside class="rounded-2xl border border-black bg-white p-6 h-fit"><h3 class="font-bold">Process request</h3><form method="POST" action="{{ route('admin.wear.returns.status',$returnRequest) }}" class="mt-5 space-y-4">@csrf<select name="status" class="w-full rounded-xl border border-black px-4 py-3 text-sm">@foreach(['under_review','approved','rejected','received','refunded','completed'] as $s)<option value="{{ $s }}" @selected($returnRequest->status===$s)>{{ ucwords(str_replace('_',' ',$s)) }}</option>@endforeach</select><textarea name="notes" rows="5" placeholder="Admin notes" class="w-full rounded-xl border border-black px-4 py-3 text-sm">{{ $returnRequest->notes }}</textarea><button class="w-full rounded-xl bg-black px-5 py-3 text-sm font-bold text-white">Save status</button></form></aside></div>
@if($returnRequest->status === 'processed' && $returnRequest->refund_status === 'pending')
<div class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5">
    <h3 class="font-bold text-black">Record completed refund</h3>
    <p class="mt-1 text-sm text-black">Enter the provider or manual refund reference only after the money has actually been refunded.</p>
    <form method="POST" action="{{ route('admin.wear.returns.refund', $returnRequest) }}" class="mt-4 flex flex-col gap-3 sm:flex-row">
        @csrf
        <input name="refund_reference" required maxlength="120" placeholder="Refund reference" class="flex-1 rounded-xl border border-black bg-white px-4 py-2.5 text-sm">
        @if(\App\Support\AdminStepUp::enabled())
            <input name="totp_code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autocomplete="one-time-code" placeholder="Authenticator code" class="rounded-xl border border-black bg-white px-4 py-2.5 text-sm sm:w-44">
        @endif
        <button class="rounded-xl bg-black px-5 py-2.5 text-sm font-semibold text-white">Record refund</button>
    </form>
</div>
@endif
@endsection
