<?php
namespace App\Http\Controllers\Api\V1\Commerce;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\V1\Commerce\AddressRequest;
use App\Http\Resources\Api\V1\AddressResource;
use App\Models\Commerce\Address;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class AddressController extends Controller { public function index(Request $r){return AddressResource::collection($r->user()->addresses()->orderByDesc('is_default')->latest()->get());} public function store(AddressRequest $r){$data=$r->validated();$address=DB::transaction(function()use($r,$data){$a=$r->user()->addresses()->create($data);$hasDefault=$r->user()->addresses()->where('type',$a->type)->where('is_default',true)->whereKeyNot($a->id)->exists();if(($data['is_default']??false)||!$hasDefault){$r->user()->addresses()->whereKeyNot($a->id)->where('type',$a->type)->update(['is_default'=>false]);$a->update(['is_default'=>true]);}return $a;});return (new AddressResource($address))->response()->setStatusCode(200);} public function update(AddressRequest $r,Address $address){abort_unless($address->user_id===$r->user()->id,403);$data=$r->validated();$address=DB::transaction(function()use($r,$data,$address){$oldType=$address->type;$address->update($data);if(($data['is_default']??false)){ $r->user()->addresses()->whereKeyNot($address->id)->where('type',$address->type)->update(['is_default'=>false]); } elseif($oldType!==$address->type || !$r->user()->addresses()->where('type',$address->type)->where('is_default',true)->exists()){ $r->user()->addresses()->whereKeyNot($address->id)->where('type',$address->type)->latest('id')->limit(1)->update(['is_default'=>true]); $address->update(['is_default'=>false]); } return $address;});return new AddressResource($address);} public function destroy(Request $r,Address $address){abort_unless($address->user_id===$r->user()->id,403);DB::transaction(function()use($r,$address){$wasDefault=(bool)$address->is_default;$type=$address->type;$address->delete();if($wasDefault&&!$r->user()->addresses()->where('type',$type)->where('is_default',true)->exists()){$next=$r->user()->addresses()->where('type',$type)->latest('id')->first();$next?->update(['is_default'=>true]);}});return response()->noContent();} }
