<?php
namespace App\Services\Cart;
use App\Enums\Commerce\CartStatus;
use App\Models\Cart\Cart;
use App\Models\Cart\CartItem;
use App\Models\User;
use App\Models\Wear\WearProductVariant;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
final class CartService { public const HEADER='X-Guest-Cart-Token'; public function current(?User $user,?string $guestToken):Cart{if($user){return Cart::firstOrCreate(['user_id'=>$user->id,'status'=>CartStatus::Active]);}$guestToken??=Str::random(64);$hash=hash('sha256',$guestToken);$cart=Cart::firstOrCreate(['guest_token_hash'=>$hash,'status'=>CartStatus::Active]);$cart->setAttribute('_guest_cart_token',$guestToken);return $cart;} public function add(Cart $cart,WearProductVariant $variant,int $quantity):Cart{$guestToken=$cart->getAttribute('_guest_cart_token');$variant->loadMissing('product');if(!$variant->product||!$variant->product->is_active)throw ValidationException::withMessages(['variant'=>'Product is unavailable.']);if($quantity<1)throw ValidationException::withMessages(['quantity'=>'Quantity must be at least 1.']);$item=CartItem::firstOrNew(['cart_id'=>$cart->id,'wear_product_variant_id'=>$variant->id]);$new=$item->exists?$item->quantity+$quantity:$quantity;if($variant->stock<$new)throw ValidationException::withMessages(['quantity'=>'Requested quantity exceeds available stock.']);$item->quantity=$new;$item->save();$fresh=$cart->fresh('items.variant.product');if(!$fresh->user_id&&$guestToken){$fresh->setAttribute('_guest_cart_token',$guestToken);}return $fresh;} public function set(Cart $cart,WearProductVariant $variant,int $quantity):Cart{$item=$cart->items()->where('wear_product_variant_id',$variant->id)->firstOrFail();if($quantity<=0){$item->delete();return $cart->fresh('items.variant.product');}if($variant->stock<$quantity)throw ValidationException::withMessages(['quantity'=>'Requested quantity exceeds available stock.']);$item->update(['quantity'=>$quantity]);return $cart->fresh('items.variant.product');} public function remove(Cart $cart,WearProductVariant $variant):Cart{$cart->items()->where('wear_product_variant_id',$variant->id)->delete();return $cart->fresh('items.variant.product');} public function clear(Cart $cart):Cart{$cart->items()->delete();return $cart->fresh('items.variant.product');} public function merge(Cart $guest,User $user):Cart{$target=$this->current($user,null);if($guest->id===$target->id)return $target->fresh('items.variant.product');foreach($guest->items()->with('variant.product')->lockForUpdate()->get() as $item){$variant=$item->variant;if(!$variant||!$variant->product?->is_active)continue;$existing=$target->items()->where('wear_product_variant_id',$item->wear_product_variant_id)->first();$quantity=min(($existing?->quantity??0)+$item->quantity,(int)$variant->stock);if($quantity<1){$existing?->delete();continue;}if($existing)$existing->update(['quantity'=>$quantity]);else $target->items()->create(['wear_product_variant_id'=>$item->wear_product_variant_id,'quantity'=>$quantity]);}$guest->update(['status'=>CartStatus::Converted,'expires_at'=>now()]);return $target->fresh('items.variant.product');} }
